# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - kubernetes
  - kubernetes-incubator
  - kubernetes-security
  - google/cadvisor
  trusted_org: kubernetes

heart:
  adorees:
  - k8s-merge-robot

slack:
  mentionchannels:
  - sig-testing
  mergewarnings:
  - repos:
    - kubernetes/kubernetes
    channels:
    - kubernetes-dev
    whitelist:
    - k8s-merge-robot

label:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  milestone_maintainers_id: 2460384

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:
  google/cadvisor:
  - trigger

  kubernetes/charts:
  - trigger

  kubernetes/heapster:
  - trigger

  kubernetes/kops:
  - trigger

  kubernetes/kubernetes:
  - trigger
  - release-note

  kubernetes/test-infra:
  - trigger
  - config-updater

  kubernetes:
  - assign
  - cla
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - size
  - yuks
  - wip
  - shrug
  - slackevents

  kubernetes-incubator:
  - cla
  - assign
  - size

  kubernetes-incubator/kube-aws:
  - lgtm

  kubernetes-incubator/external-storage:
  - label
  - lgtm

  kubernetes-security/kubernetes:
  - trigger

  spxtr/envoy:
  - assign
  - close
  - reopen
  - lgtm
  - trigger
