# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-incubator
  - kubernetes-security
  - kubernetes-sigs
  trusted_org: kubernetes
  join_org_url: "https://git.k8s.io/community/community-membership.md#member"
  only_org_members: true
- repos:
  - google/cadvisor
  - GoogleCloudPlatform/k8s-multicluster-ingress
  trusted_org: kubernetes
  join_org_url: "https://git.k8s.io/community/community-membership.md#member"
- repos:
  - containerd/cri
  join_org_url: "https://github.com/containerd/containerd/blob/master/MAINTAINERS"
- repos:
  - kubeflow
  join_org_url: "https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md"
- repos:
  - tensorflow/minigo
  join_org_url: "https://github.com/tensorflow/minigo/blob/master/CONTRIBUTING.md"
- repos:
  - bazelbuild

owners:
  mdyamlrepos:
  - kubernetes/website
  skip_collaborators:
  - kubernetes-sigs/contributor-playground
  - helm/charts

# TODO(fejta): delete these in before April
use_deprecated_2018_implicit_self_approve_default_migrate_before_july_2019: true
use_deprecated_2018_review_acts_as_approve_default_migrate_before_july_2019: true

approve:
- repos:
  - kubernetes/cloud-provider-aws
  - kubernetes/cloud-provider-azure
  - kubernetes/cluster-registry
  - kubernetes/contrib
  - kubernetes/dashboard
  - kubernetes/dns
  - kubernetes/enhancements
  - kubernetes/examples
  - kubernetes/federation
  - kubernetes/gengo
  - kubernetes/ingress-gce
  - kubernetes/ingress-nginx
  - kubernetes/klog
  - kubernetes/kube-deploy
  - kubernetes/kubeadm
  - kubernetes/kubectl
  - kubernetes/kubernetes-template-project
  - kubernetes/kube-state-metrics
  - kubernetes/minikube
  - kubernetes/node-problem-detector
  - kubernetes/perf-tests
  - kubernetes/publishing-bot
  - kubernetes/release
  - kubernetes/repo-infra
  - kubernetes/sig-release
  - kubernetes/steering
  - kubernetes/utils
  - kubernetes-incubator/ip-masq-agent
  require_self_approval: false
  lgtm_acts_as_approve: true
- repos:
  - kubernetes/kops
  - kubernetes/kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-sigs
  - client-go/unofficial-docs
  require_self_approval: false
- repos:
  - bazelbuild
  - kubernetes/community
  - kubernetes/org
  - kubernetes/test-infra
  require_self_approval: false
  ignore_review_state: false
- repos:
  - helm/charts
  require_self_approval: false
  lgtm_acts_as_approve: true

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

label:
  additional_labels:
    # This label is used by the API review process
    # https://git.k8s.io/community/sig-architecture/api-review-process.md#mechanics
    - api-review
    # These labels are used by Kubeflow
    # TODO(https://github.com/kubernetes/test-infra/issues/8648): Switch
    # to configuring prefixes and not individual labels once  that's supported.
    - community/discussion
    - community/maintenance
    - community/question
    - cuj/build-train-deploy
    - cuj/multi-user
    - platform/aws
    - platform/azure
    - platform/gcp
    - platform/minikube
    - platform/other

lgtm:
- repos:
  - bazelbuild
  review_acts_as_lgtm: true
- repos:
  - kubernetes/test-infra
  store_tree_hash: true

blockades:
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^examples/
  explanation: "examples/ has moved to https://github.com/kubernetes/examples/"
- repos:
  - kubernetes/community
  blockregexps:
  - ^events/2016
  - ^events/2017
  - ^events/elections/2017
  - ^events/elections/2018
  explanation: "These files are historical, and from events that have already occurred."
- repos:
  - kubernetes/community
  blockregexps:
  - ^keps/
  explanation: "KEPs have been relocated to [kubernetes/enhancements](https://git.k8s.io/enhancements/)! Please submit any updates there."
- repos:
  - kubernetes/enhancements
  blockregexps:
  - ^keps/NEXT_KEP_NUMBER$
  explanation: "KEP numbers are obsolete. Please remove any changes to `NEXT_KEP_NUMBER` from this PR and ensure the KEP filename is the draft date and KEP title e.g., `YYYYMMDD-pony-controller.md`"

blunderbuss:
  max_request_count: 2

cat:
  key_path: /etc/cat-api/api-key

slack:
  mergewarnings:
  - repos:
    - kubernetes/community
    - kubernetes/org
    channels:
    - sig-contribex
    whitelist:
    - k8s-ci-robot
  - repos:
    - kubernetes/enhancements
    channels:
    - sig-pm
    whitelist:
    - k8s-ci-robot
  - repos:
    - kubernetes/utils
    channels:
    - sig-architecture
    whitelist:
    - k8s-ci-robot
  - repos:
    - kubernetes/kubernetes
    channels:
    - kubernetes-dev
    whitelist:
    - k8s-ci-robot # future home of tide
    - k8s-release-robot # anago
    branch_whitelist:
        release-1.10:
            - maciekpytel # 1.10 patch release manager
        release-1.11:
            - foxish # 1.11 patch release manager
        release-1.12:
            - feiskyer # 1.12 patch release manager
        release-1.13:
            - aleksandra-malinowska # 1.13 patch release team
            - tpepper # 1.13 patch release team
        release-1.14:
            - aleksandra-malinowska # 1.14 patch release team
            - tpepper # 1.14 patch release team
            - hoegaarden # 1.14 branch manager
        feature-serverside-apply:
            - lavalamp # feature-serverside-apply "branch manager"
            - apelisse # feature-serverside-apply "branch manager"
  - repos:
    - kubernetes/test-infra
    channels:
    - testing-ops
    whitelist:
    - k8s-ci-robot

repo_milestone:
  # Default maintainer
  '':
    # You can curl the following endpoint in order to determine the github ID of your team
    # responsible for maintaining the milestones. You may need to specify the page number.
    # curl -H "Authorization: token <token>" "https://api.github.com/orgs/<org-name>/teams?page=N"
    maintainers_id: 2460384
    maintainers_team: kubernetes-milestone-maintainers
  kubernetes-sigs/cluster-api:
    maintainers_id: 3058957
    maintainers_team: cluster-api-maintainers
    maintainers_friendly_name: Cluster API Maintainers
  kubernetes-sigs/cluster-api-provider-aws:
    maintainers_id: 2830895
    maintainers_team: cluster-api-provider-aws-maintainers
    maintainers_friendly_name: Cluster API Provider AWS Maintainers
  kubernetes-sigs/cluster-api-provider-azure:
    maintainers_id: 3063852
    maintainers_team: cluster-api-provider-azure-maintainers
    maintainers_friendly_name: Cluster API Provider Azure Maintainers
  kubernetes/community:
    maintainers_id: 3169231
    maintainers_team: community-milestone-maintainers
    maintainers_friendly_name: Community Milestone Maintainers

project_config:
  project_org_configs:
    kubernetes:
      org_maintainers_team_id: 3162587
      org_maintainers_team_name: sig-testing-dummy-project-team
      org_default_column_map:
        test-infra-dummy-testing-project-plugin:
          To do
        KEP Implementation Tracking:
          To do
      project_repo_configs:
        kubernetes:
          repo_maintainers_team_id: 2460384
          repo_maintainers_team_name: kubernetes-milestone-maintainers
          repo_default_column_map:
            component-base:
              To do
            Workloads:
              Backlog
    kubeflow:
      org_maintainers_team_id: 2460384
      org_maintainers_team_name: kubernetes-milestone-maintainers

config_updater:
  maps:
    label_sync/labels.yaml:
      name: label-config
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

welcome:
- repos:
  - kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-incubator
  - kubernetes-sigs
  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. <br><br>If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to Kubernetes. :smiley:"

require_matching_label:
- missing_label: needs-kind
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^kind/
- missing_label: needs-sig
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^(sig|wg|committee)/
  # Define needs-sig separately for issues so that we only comment on issues.
- missing_label: needs-sig
  org: kubernetes
  repo: kubernetes
  issues: true
  regexp: ^(sig|wg|committee)/
  missing_comment: |
    There are no sig labels on this issue. Please add a sig label by either:

    1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
        e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR

    2. specifying the label manually: `/sig <group-name>`
        e.g., `/sig scalability` to apply the `sig/scalability` label

    Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
    The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.
- missing_label: needs-priority
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^priority/
- missing_label: needs-kind
  org: kubernetes
  repo: cloud-provider-aws
  prs: true
  regexp: ^kind/


plugins:
  # Enable the following for any bazelbuild repo (rules_k8s, rules_docker) that sends prow webhooks
  # Repos that do not send prow webhooks will see no effect.
  bazelbuild:
  - approve  # Allow OWNERS to /approve
  - assign  # Allow /assign and /cc
  - blunderbuss  # Auto-assign people
  - cat # /meow replies with cat pictures
  - dog # /bark replies with dog pictures
  - help  # Support /help and /good-first-issue
  - hold  # Support /hold to delay merge
  - lgtm  # Allow /lgtm
  - lifecycle  # Allow /lifecycle stale
  - override
  - size  # Auto-label size of PR
  - trigger  # Allow people to configure CI jobs to /test
  - verify-owners # Validates OWNERS file changes in PRs.
  - wip  # Auto-hold PRs with WIP in title
  - yuks # Let prow tell a /joke

  google/cadvisor:
  - trigger

  kubeflow:
  - approve   # Enable /approve and /assign commands.
  - assign
  - blunderbuss
  - help
  - hold
  - label
  - lgtm
  - lifecycle   # Lets PRs & issues be flagged as stale
  - size
  - skip  # Allows cleaning up stale commit statuses
  - verify-owners   # Validates OWNERS file changes in PRs.
  - wip   # Applies a label to PRs with wip in the title to block merge
  - trigger

  helm/charts:
  - approve
  - assign
  - blunderbuss
  - cla
  - hold
  - lgtm
  - trigger
  - verify-owners

  kubernetes:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - golint
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - sigmention
  - size
  - skip
  - slackevents
  - verify-owners
  - wip
  - yuks

  kubernetes/cloud-provider-aws:
  - milestone
  - milestonestatus
  - release-note
  - require-matching-label
  - welcome
  - trigger

  kubernetes/cloud-provider-azure:
  - milestone
  - milestonestatus
  - release-note
  - require-matching-label
  - welcome
  - trigger

  kubernetes/cloud-provider-gcp:
  - trigger

  kubernetes/cloud-provider-openstack:
  - trigger
  - override

  kubernetes/cloud-provider-vsphere:
  - trigger

  kubernetes/cluster-registry:
  - trigger

  kubernetes/community:
  - blockade
  - milestone
  - require-sig
  - trigger

  kubernetes/dns:
  - trigger

  kubernetes/enhancements:
  - blockade
  - milestone
  - require-sig
  - stage
  - trigger

  kubernetes/examples:
  - trigger

  kubernetes/ingress-gce:
  - trigger

  kubernetes/federation:
  - trigger

  kubernetes/kops:
  - trigger

  kubernetes/kubernetes:
  - blockade
  - cherry-pick-unapproved
  - milestone
  - milestonestatus
  - override
  - release-note
  - require-matching-label
  - trigger

  kubernetes/node-problem-detector:
  - trigger

  kubernetes/org:
  - trigger

  kubernetes/perf-tests:
  - trigger

  kubernetes/publishing-bot:
  - trigger
  - override

  kubernetes/release:
  - trigger

  kubernetes/sig-release:
  - blockade
  - milestone
  - stage

  kubernetes/test-infra:
  - config-updater
  - milestone
  - override
  - trigger
  - welcome

  kubernetes/utils:
  - override

  kubernetes-client:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-csi:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - size
  - skip
  - trigger
  - verify-owners
  - wip
  - yuks

  kubernetes-incubator:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-incubator/service-catalog:
  - trigger

  kubernetes-incubator/ip-masq-agent:
  - trigger

  kubernetes-security/kubernetes:
  - trigger

  kubernetes-sigs:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - owners-label
  - pony
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-sigs/kind:
  - override
  - trigger
  - welcome

  kubernetes-sigs/federation-v2:
  - trigger

  kubernetes-sigs/testing_frameworks:
  - trigger

  kubernetes-sigs/poseidon:
  - trigger

  kubernetes-sigs/cluster-api:
  - trigger
  - milestone

  kubernetes-sigs/cluster-api-provider-aws:
  - trigger
  - milestone

  kubernetes-sigs/cluster-api-provider-azure:
  - milestone
  - milestonestatus
  - release-note
  - require-matching-label
  - welcome
  - trigger

  kubernetes-sigs/cluster-api-provider-digitalocean:
  - trigger

  kubernetes-sigs/cluster-api-provider-gcp:
  - trigger

  kubernetes-sigs/cluster-api-provider-openstack:
  - trigger

  kubernetes-sigs/cluster-api-provider-vsphere:
  - trigger

  kubernetes-sigs/contributor-playground:
  - require-sig
  - welcome

  kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - trigger

  kubernetes-sigs/sig-storage-local-static-provisioner:
  - trigger

  kubernetes-sigs/gcp-filestore-csi-driver:
  - trigger

  kubernetes-sigs/cri-o:
  - trigger

  kubernetes-sigs/kube-storage-version-migrator:
  - trigger

  kubernetes-sigs/structured-merge-diff:
  - trigger

  kubernetes-sigs/aws-alb-ingress-controller:
  - trigger

  kubernetes-sigs/aws-ebs-csi-driver:
  - trigger

  kubernetes-sigs/kubebuilder-declarative-pattern:
  - trigger

  containerd/cri:
  - assign
  - cla
  - label
  - lgtm
  - lifecycle
  - size
  - trigger

  tensorflow/k8s:
  - trigger

  tensorflow/minigo:
  - trigger
  - lgtm
  - size

  spxtr/envoy:
  - assign
  - lgtm
  - lifecycle
  - trigger

  GoogleCloudPlatform/k8s-multicluster-ingress:
  - trigger

  GoogleCloudPlatform/k8s-cluster-bundle:
  - trigger
  - lgtm
  - size
  - welcome

  GoogleCloudPlatform/netd:
  - trigger
  - lgtm
  - golint
  - approve
  - verify-owners
  - size
  - assign
  - help
  - hold
  - cat
  - dog
  - wip

  client-go/unofficial-docs:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - help
  - hold
  - label
  - lgtm
  - verify-owners
  - wip

  cncf/apisnoop:
  - cat # /meow replies with cat pictures
  - dog # /bark replies with dog pictures

external_plugins:
  kubernetes/community:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/contrib:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/cloud-provider-openstack:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/kops:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/kubernetes:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/org:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/test-infra:
  - name: needs-rebase
    events:
      - pull_request
  client-go/unofficial-docs:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-incubator/service-catalog:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/contributor-playground:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/cluster-api-provider-azure:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/cluster-api-provider-openstack:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/kind:
  - name: needs-rebase
    events:
      - pull_request
