# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - kubernetes
  - kubernetes-incubator
  - kubernetes-security
  - google/cadvisor
  - tensorflow/k8s
  - GoogleCloudPlatform/k8s-multicluster-ingress
  trusted_org: kubernetes
  join_org_url: "https://github.com/kubernetes/community/blob/master/community-membership.md#member"

approve:
- repos:
  - kubernetes/charts
  - kubernetes/cluster-registry
  - kubernetes/community
  - kubernetes/kubectl
  - kubernetes/sig-release
  - kubernetes/steering
  - kubernetes/test-infra
  implicit_self_approve: true
- repos:
  - kubernetes/kubernetes
  implicit_self_approve: true
  issue_required: true

blockades:
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/man
  exceptionregexps:
  - ^docs/man/man1/.*\.1$
  explanation: "Files under `docs/man` must be in the `man1` directory and have suffix `.1`."
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/user-guide
  exceptionregexps:
  - ^docs/user-guide/kubectl/kubectl.*\.md$
  explanation: "Files under `docs/user-guide` must be in the `kubectl` directory and match pattern `kubectl*.md`."
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/yaml
  exceptionregexps:
  - ^docs/yaml/kubectl/kubectl_.*\.yaml$
  explanation: "Files under `docs/yaml` must be in the `kubectl` directory and match pattern `kubectl_*.yaml`."
- repos:
  - kubernetes/community
  blockregexps:
  - ^events/2016
  - ^events/elections/2017
  explanation: "These files are historical, and from events that have already occurred."

heart:
  adorees:
  - k8s-merge-robot

slack:
  mergewarnings:
  - repos:
    - kubernetes/kubernetes
    channels:
    - kubernetes-dev
    whitelist:
    - k8s-merge-robot
    - wojtek-t # 1.7 patch release manager
    - jpbetz # 1.8 patch release manager
    - mbohlool # 1.9 patch release manager
  - repos:
    - kubernetes/test-infra
    channels:
    - testing-ops
    whitelist:
    - k8s-ci-robot

milestonestatus:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  maintainers_id: 2460384

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:
  google/cadvisor:
  - trigger

  kubernetes/charts:
  - approve
  - blunderbuss
  - trigger

  kubernetes/cluster-registry:
  - approve
  - trigger

  kubernetes/community:
  - approve
  - blunderbuss
  - blockade
  - require-sig
  - trigger

  kubernetes/contrib:
  - approve
  - blunderbuss

  kubernetes/dns:
  - trigger

  kubernetes/ingress-gce:
  - trigger

  kubernetes/federation:
  - trigger
  - approve

  kubernetes/heapster:
  - trigger

  kubernetes/kops:
  - trigger
  - approve

  kubernetes/kubectl:
  - approve

  kubernetes/kubernetes:
  - approve
  - blockade
  - docs-no-retest
  - release-note
  - require-sig
  - trigger

  kubernetes/kubernetes-template-project:
  - approve

  kubernetes/sig-release:
  - approve

  kubernetes/steering:
  - approve

  kubernetes/test-infra:
  - trigger
  - config-updater
  - approve

  kubernetes:
  - assign
  - cla
  - golint
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - milestonestatus
  - shrug
  - sigmention
  - size
  - slackevents
  - wip
  - yuks

  kubernetes-incubator:
  - assign
  - cla
  - label
  - lgtm
  - lifecycle
  - size

  kubernetes-incubator/cri-containerd:
  - trigger

  kubernetes-security/kubernetes:
  - trigger

  tensorflow/k8s:
  - trigger

  spxtr/envoy:
  - assign
  - lgtm
  - lifecycle
  - trigger

  GoogleCloudPlatform/k8s-multicluster-ingress:
  - trigger
