# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - kubernetes
  - kubernetes-incubator
  - kubernetes-security
  - google/cadvisor
  - tensorflow/k8s
  trusted_org: kubernetes

heart:
  adorees:
  - k8s-merge-robot

slack:
  mergewarnings:
  - repos:
    - kubernetes/kubernetes
    channels:
    - kubernetes-dev
    whitelist:
    - k8s-merge-robot

milestonestatus:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  maintainers_id: 2460384

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:
  google/cadvisor:
  - trigger

  kubernetes/charts:
  - trigger

  kubernetes/cluster-registry:
  - trigger

  kubernetes/community:
  - trigger

  kubernetes/federation:
  - trigger

  kubernetes/heapster:
  - trigger

  kubernetes/kops:
  - trigger

  kubernetes/kubernetes:
  - trigger
  - release-note
  - docs-no-retest

  kubernetes/test-infra:
  - trigger
  - config-updater

  kubernetes:
  - assign
  - cla
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  - milestonestatus
  - sigmention
  - size
  - yuks
  - wip
  - shrug
  - slackevents

  kubernetes-incubator:
  - assign
  - cla
  - close
  - label
  - lgtm
  - reopen
  - size

  kubernetes-incubator/cri-containerd:
  - trigger

  kubernetes-security/kubernetes:
  - trigger

  tensorflow/k8s:
  - trigger

  spxtr/envoy:
  - assign
  - close
  - reopen
  - lgtm
  - trigger
