# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-incubator
  - kubernetes-security
  - kubernetes-sigs
  trusted_org: kubernetes
  join_org_url: "https://git.k8s.io/community/community-membership.md#member"
  only_org_members: true
- repos:
  - google/cadvisor
  - GoogleCloudPlatform/k8s-multicluster-ingress
  trusted_org: kubernetes
  join_org_url: "https://git.k8s.io/community/community-membership.md#member"
- repos:
  - containerd/cri
  join_org_url: "https://github.com/containerd/containerd/blob/master/MAINTAINERS"
- repos:
  - kubeflow
  join_org_url: "https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md"
- repos:
  - tensorflow/minigo
  join_org_url: "https://github.com/tensorflow/minigo/blob/master/CONTRIBUTING.md"
- repos:
  - bazelbuild

owners:
  mdyamlrepos:
  - kubernetes/website
  skip_collaborators:
  - kubernetes-sigs/contributor-playground
  - helm/charts

approve:
- repos:
  - kubernetes/cloud-provider-aws
  - kubernetes/cloud-provider-azure
  - kubernetes/cluster-registry
  - kubernetes/contrib
  - kubernetes/dashboard
  - kubernetes/dns
  - kubernetes/enhancements
  - kubernetes/examples
  - kubernetes/federation
  - kubernetes/gengo
  - kubernetes/ingress-gce
  - kubernetes/ingress-nginx
  - kubernetes/klog
  - kubernetes/kops
  - kubernetes/kube-deploy
  - kubernetes/kubeadm
  - kubernetes/kubectl
  - kubernetes/kubernetes-template-project
  - kubernetes/kube-state-metrics
  - kubernetes/minikube
  - kubernetes/node-problem-detector
  - kubernetes/perf-tests
  - kubernetes/publishing-bot
  - kubernetes/release
  - kubernetes/repo-infra
  - kubernetes/sig-release
  - kubernetes/steering
  - kubernetes/test-infra
  - kubernetes/utils
  - kubernetes-incubator/ip-masq-agent
  implicit_self_approve: true
  lgtm_acts_as_approve: true
- repos:
  - kubernetes/kubernetes
  - kubernetes-client
  - kubernetes-csi
  - kubernetes-sigs
  - client-go/unofficial-docs
  implicit_self_approve: true
- repos:
  - bazelbuild
  implicit_self_approve: true
  review_acts_as_approve: true
- repos:
  - helm/charts
  implicit_self_approve: true
  lgtm_acts_as_approve: true

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

lgtm:
- repos:
  - bazelbuild
  review_acts_as_lgtm: true
- repos:
  - kubernetes/test-infra
  store_tree_hash: true

blockades:
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/man
  exceptionregexps:
  - ^docs/man/man1/.*\.1$
  explanation: "Files under `docs/man` must be in the `man1` directory and have suffix `.1`."
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/user-guide
  exceptionregexps:
  - ^docs/user-guide/kubectl/kubectl.*\.md$
  explanation: "Files under `docs/user-guide` must be in the `kubectl` directory and match pattern `kubectl*.md`."
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^docs/yaml
  exceptionregexps:
  - ^docs/yaml/kubectl/kubectl_.*\.yaml$
  explanation: "Files under `docs/yaml` must be in the `kubectl` directory and match pattern `kubectl_*.yaml`."
- repos:
  - kubernetes/kubernetes
  blockregexps:
  - ^examples/
  explanation: "examples/ has moved to https://github.com/kubernetes/examples/"
- repos:
  - kubernetes/community
  blockregexps:
  - ^events/2016
  - ^events/2017
  - ^events/elections/2017
  - ^events/elections/2018
  explanation: "These files are historical, and from events that have already occurred."
- repos:
  - kubernetes/community
  blockregexps:
  - ^keps/
  explanation: "KEPs have been relocated to [kubernetes/enhancements](https://git.k8s.io/enhancements/)! Please submit any updates there."

blunderbuss:
  max_request_count: 2

cat:
  key_path: /etc/cat-api/api-key

slack:
  mergewarnings:
  - repos:
    - kubernetes/community
    - kubernetes/org
    channels:
    - sig-contribex
    whitelist:
    - k8s-ci-robot
  - repos:
    - kubernetes/kubernetes
    channels:
    - kubernetes-dev
    whitelist:
    - k8s-ci-robot # future home of tide
    - k8s-release-robot # anago
    branch_whitelist:
        release-1.8:
            - jpbetz # 1.8 patch release manager
        release-1.9:
            - mbohlool # 1.9 patch release manager
        release-1.10:
            - maciekpytel # 1.10 patch release manager
        release-1.11:
            - foxish # 1.11 patch release manager
        release-1.12:
            - feiskyer # 1.12 patch release manager
        release-1.13:
            - dougm # 1.13 branch manager
            - hoegaarden # 1.13 branch manager shadow
            - idealhack # 1.13 branch manager shadow
        feature-serverside-apply:
            - lavalamp # feature-serverside-apply "branch manager"
            - apelisse # feature-serverside-apply "branch manager"
  - repos:
    - kubernetes/test-infra
    channels:
    - testing-ops
    whitelist:
    - k8s-ci-robot

repo_milestone:
  # Default maintainer
  '':
    # You can curl the following endpoint in order to determine the github ID of your team
    # responsible for maintaining the milestones:
    # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
    maintainers_id: 2460384
    maintainers_team: kubernetes-milestone-maintainers

config_updater:
  maps:
    label_sync/labels.yaml:
      name: label-config
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

welcome:
- repos:
  - kubernetes/test-infra
  message_template: "Welcome @{{.AuthorLogin}}! It looks like this is your first PR to {{.Org}}/{{.Repo}} 🎉🎉"

require_matching_label:
- missing_label: needs-kind
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^kind/
- missing_label: needs-sig
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^(sig|wg|committee)/
  # Define needs-sig separately for issues so that we only comment on issues.
- missing_label: needs-sig
  org: kubernetes
  repo: kubernetes
  issues: true
  regexp: ^(sig|wg|committee)/
  missing_comment: |
    There are no sig labels on this issue. Please add a sig label by either:

    1. mentioning a sig: `@kubernetes/sig-<group-name>-<group-suffix>`
        e.g., `@kubernetes/sig-contributor-experience-<group-suffix>` to notify the contributor experience sig, OR

    2. specifying the label manually: `/sig <group-name>`
        e.g., `/sig scalability` to apply the `sig/scalability` label

    Note: Method 1 will trigger an email to the group. See the [group list](https://git.k8s.io/community/sig-list.md).
    The `<group-suffix>` in method 1 has to be replaced with one of these: _**bugs, feature-requests, pr-reviews, test-failures, proposals**_.
- missing_label: needs-priority
  org: kubernetes
  repo: kubernetes
  prs: true
  regexp: ^priority/
- missing_label: needs-kind
  org: kubernetes
  repo: cloud-provider-aws
  prs: true
  regexp: ^kind/


plugins:
  # Enable the following for any bazelbuild repo (rules_k8s, rules_docker) that sends prow webhooks
  # Repos that do not send prow webhooks will see no effect.
  bazelbuild:
  - approve  # Allow OWNERS to /approve
  - assign  # Allow /assign and /cc
  - blunderbuss  # Auto-assign people
  - cat # /meow replies with cat pictures
  - dog # /bark replies with dog pictures
  - help  # Support /help and /good-first-issue
  - hold  # Support /hold to delay merge
  - lgtm  # Allow /lgtm
  - lifecycle  # Allow /lifecycle stale
  - override
  - size  # Auto-label size of PR
  - trigger  # Allow people to configure CI jobs to /test
  - verify-owners # Validates OWNERS file changes in PRs.
  - wip  # Auto-hold PRs with WIP in title
  - yuks # Let prow tell a /joke

  google/cadvisor:
  - trigger

  kubeflow:
  - approve   # Enable /approve and /assign commands.
  - assign
  - blunderbuss
  - help
  - hold
  - label
  - lgtm
  - lifecycle   # Lets PRs & issues be flagged as stale
  - size
  - skip  # Allows cleaning up stale commit statuses
  - verify-owners   # Validates OWNERS file changes in PRs.
  - wip   # Applies a label to PRs with wip in the title to block merge
  - trigger

  helm/charts:
  - approve
  - assign
  - blunderbuss
  - cla
  - hold
  - lgtm
  - trigger
  - verify-owners

  kubernetes:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - golint
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - shrug
  - sigmention
  - size
  - skip
  - slackevents
  - verify-owners
  - wip
  - yuks

  kubernetes/cloud-provider-aws:
  - milestone
  - milestonestatus
  - owners-label
  - release-note
  - require-matching-label
  - welcome
  - trigger

  kubernetes/cloud-provider-azure:
  - trigger

  kubernetes/cloud-provider-gcp:
  - trigger

  kubernetes/cloud-provider-openstack:
  - trigger
  - override

  kubernetes/cloud-provider-vsphere:
  - trigger

  kubernetes/cluster-registry:
  - trigger

  kubernetes/community:
  - blockade
  - owners-label
  - require-sig
  - trigger

  kubernetes/dns:
  - trigger

  kubernetes/enhancements:
  - blockade
  - milestone
  - owners-label
  - require-sig
  - stage

  kubernetes/examples:
  - trigger

  kubernetes/ingress-gce:
  - trigger

  kubernetes/federation:
  - trigger

  kubernetes/kops:
  - trigger

  kubernetes/kubernetes:
  - blockade
  - cherry-pick-unapproved
  - milestone
  - milestonestatus
  - owners-label
  - release-note
  - require-matching-label
  - trigger

  kubernetes/org:
  - owners-label
  - trigger

  kubernetes/perf-tests:
  - trigger

  kubernetes/publishing-bot:
  - trigger

  kubernetes/release:
  - trigger

  kubernetes/sig-release:
  - blockade
  - owners-label
  - stage

  kubernetes/test-infra:
  - config-updater
  - milestone
  - owners-label
  - override
  - trigger
  - welcome

  kubernetes/website:
  - owners-label

  kubernetes-client:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-csi:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-csi/csi-lib-utils:
  - trigger

  kubernetes-incubator:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-incubator/service-catalog:
  - trigger

  kubernetes-incubator/ip-masq-agent:
  - trigger

  kubernetes-security/kubernetes:
  - trigger

  kubernetes-sigs:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - shrug
  - size
  - skip
  - verify-owners
  - wip
  - yuks

  kubernetes-sigs/kind:
  - trigger
  - welcome

  kubernetes-sigs/federation-v2:
  - trigger

  kubernetes-sigs/testing_frameworks:
  - trigger

  kubernetes-sigs/poseidon:
  - trigger

  kubernetes-sigs/cluster-api:
  - trigger

  kubernetes-sigs/cluster-api-provider-aws:
  - trigger

  kubernetes-sigs/cluster-api-provider-digitalocean:
  - trigger

  kubernetes-sigs/cluster-api-provider-gcp:
  - trigger

  kubernetes-sigs/cluster-api-provider-openstack:
  - trigger

  kubernetes-sigs/cluster-api-provider-vsphere:
  - trigger

  kubernetes-sigs/contributor-playground:
  - require-sig
  - welcome

  kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - trigger

  kubernetes-sigs/gcp-filestore-csi-driver:
  - trigger

  kubernetes-sigs/cri-o:
  - trigger

  kubernetes-sigs/kube-storage-version-migrator:
  - trigger

  kubernetes-sigs/structured-merge-diff:
  - trigger

  kubernetes-sigs/aws-alb-ingress-controller:
  - trigger

  kubernetes-sigs/aws-ebs-csi-driver:
  - trigger

  containerd/cri:
  - assign
  - cla
  - label
  - lgtm
  - lifecycle
  - size
  - trigger

  tensorflow/k8s:
  - trigger

  tensorflow/minigo:
  - trigger
  - lgtm
  - size

  spxtr/envoy:
  - assign
  - lgtm
  - lifecycle
  - trigger

  GoogleCloudPlatform/k8s-multicluster-ingress:
  - trigger

  GoogleCloudPlatform/k8s-cluster-bundle:
  - trigger
  - lgtm
  - size
  - welcome

  client-go/unofficial-docs:
  - approve
  - assign
  - blunderbuss
  - cat
  - cla
  - dog
  - help
  - hold
  - label
  - lgtm
  - verify-owners
  - wip

  cncf/apisnoop:
  - cat # /meow replies with cat pictures
  - dog # /bark replies with dog pictures

external_plugins:
  kubernetes/community:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/contrib:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/kops:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/kubernetes:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/org:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes/test-infra:
  - name: needs-rebase
    events:
      - pull_request
  client-go/unofficial-docs:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-incubator/service-catalog:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/contributor-playground:
  - name: needs-rebase
    events:
      - pull_request
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: needs-rebase
    events:
      - pull_request
