apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: test-pods
spec:
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: gcr.io/k8s-testimages/reaper:v20190621-ff01381
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=gce-project,gke-project,gpu-project,ingress-project,istio-project,scalability-project,aws-account
