apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: branchprotector
spec:
  schedule: "54 11 * * *"  # Run every day at 1154
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: branchprotector
    spec:
      template:
        spec:
          containers:
          - name: branchprotector
            image: gcr.io/k8s-prow/branchprotector:v20180302-0064877cc
            args:
            - --config-path=/etc/config/config
            - --github-token-path=/etc/github/oauth
            - --confirm
            volumeMounts:
            - name: oauth
              mountPath: /etc/github
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: oauth
            secret:
              secretName: oauth-token
          - name: config
            configMap:
              name: config
