apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinker
  labels:
    app: sinker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      containers:
      - name: sinker
        args:
        - --build-cluster=/etc/cluster/cluster
        image: gcr.io/k8s-prow/sinker:v20180302-0064877cc
        volumeMounts:
        - mountPath: /etc/cluster
          name: cluster
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: cluster
        secret:
          defaultMode: 420
          secretName: build-cluster
      - name: config
        configMap:
          name: config
