apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splice
  labels:
    app: splice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splice
    spec:
      nodeSelector:
        role: prow
      containers:
      - name: splice
        image: gcr.io/k8s-prow/splice:0.15
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        args:
        - -log-json
        env:
        - name: LINE_IMAGE
          value: "gcr.io/k8s-prow/line:0.83"
        - name: DRY_RUN
          value: "false"
      volumes:
      - name: config
        configMap:
          name: config
