apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splice
  labels:
    app: splice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splice
    spec:
      containers:
      - name: splice
        image: gcr.io/k8s-prow/splice:v20180620-3b98af6f3
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
