apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splice
  labels:
    app: splice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: splice
    spec:
      nodeSelector:
        role: ciongke
      containers:
      - name: splice
        image: gcr.io/kubernetes-jenkins-pull/splice:0.1
        volumeMounts:
        - name: job-configs
          mountPath: /etc/jobs
          readOnly: true
        env:
        - name: LINE_IMAGE
          value: "gcr.io/kubernetes-jenkins-pull/line:0.30"
        - name: DRY_RUN
          value: "false"
      volumes:
      - name: job-configs
        configMap:
          name: job-configs
 
