orgs:
  fejtaverse:
    description: very-fancy
    default_repository_permission: read
    has_organization_projects: false
    has_repository_projects: true
    admins:
    - fejta
    - k8s-ci-robot
    members:
    - fejta-bot
    - cblecker
    - bentheelder
    - krzyzacy
    - cjwagner
    teams:
      bots:
        members:
        - fejta-bot
        maintainers:
        - k8s-ci-robot
        teams:
          robots:
            members: ["fejta-bot"]
      humans:
        maintainers:
        - fejta
        members:
        - bentheelder
        - cblecker
        superlative-humans:
          members:
          - krzyzacy
