apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prow-monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: 'blackbox'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://prow.k8s.io
          - https://monitoring.prow.k8s.io
          - https://testgrid.k8s.io
          - https://gubernator.k8s.io
          - https://gubernator.k8s.io/pr/fejta # Deep health check of someone's PR dashboard.
          - https://storage.googleapis.com/k8s-gubernator/triage/index.html
          - https://storage.googleapis.com/test-infra-oncall/oncall.html
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-prober
type: Opaque
